# Generated by Django 4.2.7 on 2023-12-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0003_rename_cartid_cart_cart_id_rename_cart_cartitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Cart',
            new_name='cart',
        ),
    ]
