# Generated by Django 4.2.7 on 2023-12-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0004_rename_cart_cartitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart',
            new_name='carts',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='Cart',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='Cartitem',
        ),
    ]
