# Generated by Django 4.2.7 on 2023-12-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0005_rename_cart_cartitem_carts_alter_cart_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='Product',
        ),
    ]
