# Generated by Django 4.2.7 on 2023-12-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0006_rename_product_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Product',
            new_name='product',
        ),
    ]
