# Generated by Django 4.2.7 on 2023-12-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0007_rename_product_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='carts',
            new_name='cart',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='CartItem',
        ),
    ]
