# Generated by Django 4.2.7 on 2023-12-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0009_rename_product_cartitem_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='products',
            new_name='product',
        ),
    ]
