# Generated by Django 4.2.7 on 2023-12-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0010_rename_products_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='products',
        ),
    ]
